version: '3.8'

services:
  backend:
    build:
      context: ./BackEnd_Api
    ports:
      - "7064:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=db;Database=CrimeInvestigationSystem;User=sa;Password=Huy0307@;TrustServerCertificate=True;

  frontend:
    build:
      context: ./FrontEnd_App
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: Huy0307@
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql

volumes:
  db_data: