// <auto-generated />
using System;
using BackEnd_Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd_Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250701082848_UpdateReportNull")]
    partial class UpdateReportNull
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackEnd_Api.Models.Arrest", b =>
                {
                    b.Property<string>("SuspectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CaseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ArrestEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ArrestStartTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OfficerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SuspectMirandaSignature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SuspectId", "CaseId");

                    b.HasIndex("CaseId");

                    b.HasIndex("OfficerId");

                    b.ToTable("Arrests");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Case", b =>
                {
                    b.Property<string>("CaseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeCase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CaseId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("BackEnd_Api.Models.CaseEvidence", b =>
                {
                    b.Property<string>("CaseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EvidenceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("CaseId", "EvidenceId");

                    b.HasIndex("EvidenceId");

                    b.ToTable("CaseEvidences");
                });

            modelBuilder.Entity("BackEnd_Api.Models.CaseResult", b =>
                {
                    b.Property<string>("CaseResultId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdentifyMotive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ReportAnalyst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CaseResultId");

                    b.HasIndex("CaseId");

                    b.ToTable("CaseResults");
                });

            modelBuilder.Entity("BackEnd_Api.Models.DigitalInvest", b =>
                {
                    b.Property<string>("EvidenceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AnalystTool")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttachedFiles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("EvidenceId");

                    b.ToTable("DigitalInvests");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Event", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SuspectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("TimeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeStart")
                        .HasColumnType("datetime2");

                    b.HasKey("EventId");

                    b.HasIndex("CaseId");

                    b.HasIndex("SuspectId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Evidence", b =>
                {
                    b.Property<string>("EvidenceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AttachedFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CollectedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CurrentLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MeasureSurveyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReportId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeEvidence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarrantResultId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EvidenceId");

                    b.HasIndex("CollectedBy");

                    b.HasIndex("MeasureSurveyId");

                    b.HasIndex("ReportId");

                    b.HasIndex("WarrantResultId");

                    b.ToTable("Evidences");
                });

            modelBuilder.Entity("BackEnd_Api.Models.FinancialInvest", b =>
                {
                    b.Property<string>("EvidenceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AttachedFiles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EvidenceId");

                    b.ToTable("FinancialInvests");
                });

            modelBuilder.Entity("BackEnd_Api.Models.ForensicInvest", b =>
                {
                    b.Property<string>("EvidenceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LabName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportFiles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EvidenceId");

                    b.ToTable("ForensicInvests");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Indictment", b =>
                {
                    b.Property<string>("IndictmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProsecutionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IndictmentId");

                    b.HasIndex("ProsecutionId");

                    b.ToTable("Indictments");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Inmate", b =>
                {
                    b.Property<string>("InmateId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssignedFacility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpectedRelease")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SentenceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InmateId");

                    b.HasIndex("SentenceId");

                    b.ToTable("Inmates");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Interview", b =>
                {
                    b.Property<string>("InterviewId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AttachedFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("IntervieweeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterviewerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InvestigationPlanId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TypeInterviewee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InterviewId");

                    b.HasIndex("InterviewerId");

                    b.HasIndex("InvestigationPlanId");

                    b.ToTable("Interviews");
                });

            modelBuilder.Entity("BackEnd_Api.Models.InvestigationPlan", b =>
                {
                    b.Property<string>("InvestigationPlanId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedOfficerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DeadlineDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PlanContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InvestigationPlanId");

                    b.HasIndex("CaseId");

                    b.HasIndex("CreatedOfficerId");

                    b.ToTable("InvestigationPlans");
                });

            modelBuilder.Entity("BackEnd_Api.Models.MeasureSurvey", b =>
                {
                    b.Property<string>("MeasureSurveyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MeasureSurveyId");

                    b.ToTable("MeasureSurveys");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Permission", b =>
                {
                    b.Property<string>("PermissionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("PermissionId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("BackEnd_Api.Models.PhysicalInvest", b =>
                {
                    b.Property<string>("EvidenceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("EvidenceId");

                    b.ToTable("PhysicalInvests");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Prosecution", b =>
                {
                    b.Property<string>("ProsecutionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DecisionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ProsecutorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProsecutionId");

                    b.HasIndex("CaseId");

                    b.HasIndex("ProsecutorId");

                    b.ToTable("Prosecutions");
                });

            modelBuilder.Entity("BackEnd_Api.Models.ProsecutionSuspect", b =>
                {
                    b.Property<string>("ProsecutionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SuspectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("ProsecutionId", "SuspectId");

                    b.HasIndex("SuspectId");

                    b.ToTable("ProsecutionSuspects");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Question", b =>
                {
                    b.Property<string>("QuestionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InterviewId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Reliability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("InterviewId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("BackEnd_Api.Models.RecordInfo", b =>
                {
                    b.Property<string>("RecordInfoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCollected")
                        .HasColumnType("datetime2");

                    b.Property<string>("EvidenceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecordInfoId");

                    b.HasIndex("EvidenceId");

                    b.ToTable("RecordInfos");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Report", b =>
                {
                    b.Property<string>("ReportId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CaseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CaseLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OfficerApproveId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReporterEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReporterFullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReporterPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeReport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReportId");

                    b.HasIndex("CaseId");

                    b.HasIndex("OfficerApproveId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("BackEnd_Api.Models.ReportSuspect", b =>
                {
                    b.Property<string>("ReportId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SuspectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("ReportId", "SuspectId");

                    b.HasIndex("SuspectId");

                    b.ToTable("ReportSuspects");
                });

            modelBuilder.Entity("BackEnd_Api.Models.ReportVictim", b =>
                {
                    b.Property<string>("ReportId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VictimId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("ReportId", "VictimId");

                    b.HasIndex("VictimId");

                    b.ToTable("ReportVictims");
                });

            modelBuilder.Entity("BackEnd_Api.Models.ReportWitness", b =>
                {
                    b.Property<string>("ReportId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WitnessId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("ReportId", "WitnessId");

                    b.HasIndex("WitnessId");

                    b.ToTable("ReportWitness");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Role", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("BackEnd_Api.Models.RolePermission", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PermissionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("BackEnd_Api.Models.SceneDescription", b =>
                {
                    b.Property<string>("SceneDescriptionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SceneDescriptionId");

                    b.HasIndex("CaseId");

                    b.HasIndex("Provider");

                    b.ToTable("SceneDescriptions");
                });

            modelBuilder.Entity("BackEnd_Api.Models.SceneMedia", b =>
                {
                    b.Property<string>("SceneMediaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CapturedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateTaken")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SceneSketchUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SceneMediaId");

                    b.HasIndex("CapturedBy");

                    b.HasIndex("CaseId");

                    b.ToTable("SceneMedias");
                });

            modelBuilder.Entity("BackEnd_Api.Models.SceneProtection", b =>
                {
                    b.Property<string>("SceneProtectionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AttachedFiles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LOcationCover")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeStart")
                        .HasColumnType("datetime2");

                    b.HasKey("SceneProtectionId");

                    b.HasIndex("CaseId");

                    b.ToTable("SceneProtections");
                });

            modelBuilder.Entity("BackEnd_Api.Models.SceneSuport", b =>
                {
                    b.Property<string>("SceneSuportId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AttachedFiles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LocationAssigned")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeSuport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SceneSuportId");

                    b.HasIndex("CaseId");

                    b.ToTable("SceneSuports");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Sentence", b =>
                {
                    b.Property<string>("SentenceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CaseResultId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SentenceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentencingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SentenceId");

                    b.HasIndex("CaseId");

                    b.HasIndex("CaseResultId");

                    b.ToTable("Sentences");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Suspect", b =>
                {
                    b.Property<string>("SuspectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CatchTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("FingerPrintsHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MugshotUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("National")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SuspectId");

                    b.HasIndex("CaseId");

                    b.ToTable("Suspects");
                });

            modelBuilder.Entity("BackEnd_Api.Models.SuspectEvidence", b =>
                {
                    b.Property<string>("SuspectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EvidenceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("SuspectId", "EvidenceId");

                    b.HasIndex("EvidenceId");

                    b.ToTable("SuspectEvidences");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Timeline", b =>
                {
                    b.Property<string>("TimelineId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttachedFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseResultId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("TimelineId");

                    b.HasIndex("CaseResultId");

                    b.ToTable("Timelines");
                });

            modelBuilder.Entity("BackEnd_Api.Models.User", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAttended")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserName");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BackEnd_Api.Models.UserCase", b =>
                {
                    b.Property<string>("OfficerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CaseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Responsible")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OfficerId", "CaseId");

                    b.HasIndex("CaseId");

                    b.ToTable("UserCases");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Victim", b =>
                {
                    b.Property<string>("VictimId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Injuries")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VictimId");

                    b.HasIndex("CaseId");

                    b.ToTable("Victims");
                });

            modelBuilder.Entity("BackEnd_Api.Models.VictimEvidence", b =>
                {
                    b.Property<string>("VictimId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EvidenceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("VictimId", "EvidenceId");

                    b.HasIndex("EvidenceId");

                    b.ToTable("VictimEvidences");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Warrant", b =>
                {
                    b.Property<string>("WarrantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AttachedFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoliceReponse")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TimePublish")
                        .HasColumnType("datetime2");

                    b.Property<string>("WarrantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WarrantId");

                    b.HasIndex("CaseId");

                    b.HasIndex("PoliceReponse");

                    b.ToTable("Warrants");
                });

            modelBuilder.Entity("BackEnd_Api.Models.WarrantEvidence", b =>
                {
                    b.Property<string>("WarrantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EvidenceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("WarrantId", "EvidenceId");

                    b.HasIndex("EvidenceId");

                    b.ToTable("WarrantEvidences");
                });

            modelBuilder.Entity("BackEnd_Api.Models.WarrantResult", b =>
                {
                    b.Property<string>("WarrantResultId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoliceResponse")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("TimeActive")
                        .HasColumnType("datetime2");

                    b.Property<string>("WarrantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("WarrantResultId");

                    b.HasIndex("PoliceResponse");

                    b.HasIndex("WarrantId");

                    b.ToTable("WarrantResults");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Witness", b =>
                {
                    b.Property<string>("WitnessId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WitnessId");

                    b.HasIndex("CaseId");

                    b.ToTable("Witnesses");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Arrest", b =>
                {
                    b.HasOne("BackEnd_Api.Models.Case", "Case")
                        .WithMany("Arrests")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BackEnd_Api.Models.User", "User")
                        .WithMany("Arrests")
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackEnd_Api.Models.Suspect", "Suspect")
                        .WithMany("Arrests")
                        .HasForeignKey("SuspectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("Suspect");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackEnd_Api.Models.CaseEvidence", b =>
                {
                    b.HasOne("BackEnd_Api.Models.Case", "Case")
                        .WithMany("CaseEvidences")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackEnd_Api.Models.Evidence", "Evidence")
                        .WithMany("CaseEvidences")
                        .HasForeignKey("EvidenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("BackEnd_Api.Models.CaseResult", b =>
                {
                    b.HasOne("BackEnd_Api.Models.Case", "Case")
                        .WithMany("CaseResults")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("BackEnd_Api.Models.DigitalInvest", b =>
                {
                    b.HasOne("BackEnd_Api.Models.Evidence", "Evidence")
                        .WithOne("DigitalInvest")
                        .HasForeignKey("BackEnd_Api.Models.DigitalInvest", "EvidenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Event", b =>
                {
                    b.HasOne("BackEnd_Api.Models.Case", "Case")
                        .WithMany("Events")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd_Api.Models.Suspect", "Suspect")
                        .WithMany("Events")
                        .HasForeignKey("SuspectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("Suspect");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Evidence", b =>
                {
                    b.HasOne("BackEnd_Api.Models.User", "User")
                        .WithMany("Evidences")
                        .HasForeignKey("CollectedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackEnd_Api.Models.MeasureSurvey", "MeasureSurvey")
                        .WithMany("Evidences")
                        .HasForeignKey("MeasureSurveyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BackEnd_Api.Models.Report", "Report")
                        .WithMany("Evidences")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BackEnd_Api.Models.WarrantResult", "WarrantResult")
                        .WithMany("Evidences")
                        .HasForeignKey("WarrantResultId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MeasureSurvey");

                    b.Navigation("Report");

                    b.Navigation("User");

                    b.Navigation("WarrantResult");
                });

            modelBuilder.Entity("BackEnd_Api.Models.FinancialInvest", b =>
                {
                    b.HasOne("BackEnd_Api.Models.Evidence", "Evidence")
                        .WithOne("FinancialInvest")
                        .HasForeignKey("BackEnd_Api.Models.FinancialInvest", "EvidenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("BackEnd_Api.Models.ForensicInvest", b =>
                {
                    b.HasOne("BackEnd_Api.Models.Evidence", "Evidence")
                        .WithOne("ForensicInvest")
                        .HasForeignKey("BackEnd_Api.Models.ForensicInvest", "EvidenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Indictment", b =>
                {
                    b.HasOne("BackEnd_Api.Models.Prosecution", "Prosecution")
                        .WithMany("Indictments")
                        .HasForeignKey("ProsecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prosecution");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Inmate", b =>
                {
                    b.HasOne("BackEnd_Api.Models.Sentence", "Sentence")
                        .WithMany("Inmates")
                        .HasForeignKey("SentenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sentence");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Interview", b =>
                {
                    b.HasOne("BackEnd_Api.Models.User", "User")
                        .WithMany("Interviews")
                        .HasForeignKey("InterviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackEnd_Api.Models.InvestigationPlan", "InvestigationPlan")
                        .WithMany("Interviews")
                        .HasForeignKey("InvestigationPlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("InvestigationPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackEnd_Api.Models.InvestigationPlan", b =>
                {
                    b.HasOne("BackEnd_Api.Models.Case", "Case")
                        .WithMany("InvestigationPlans")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackEnd_Api.Models.User", "CreatedOfficer")
                        .WithMany("InvestigationPlans")
                        .HasForeignKey("CreatedOfficerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("CreatedOfficer");
                });

            modelBuilder.Entity("BackEnd_Api.Models.PhysicalInvest", b =>
                {
                    b.HasOne("BackEnd_Api.Models.Evidence", "Evidence")
                        .WithOne("PhysicalInvest")
                        .HasForeignKey("BackEnd_Api.Models.PhysicalInvest", "EvidenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Prosecution", b =>
                {
                    b.HasOne("BackEnd_Api.Models.Case", "Case")
                        .WithMany("Prosecutions")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd_Api.Models.User", "Prosecutor")
                        .WithMany("Prosecutions")
                        .HasForeignKey("ProsecutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("Prosecutor");
                });

            modelBuilder.Entity("BackEnd_Api.Models.ProsecutionSuspect", b =>
                {
                    b.HasOne("BackEnd_Api.Models.Prosecution", "Prosecution")
                        .WithMany("ProsecutionSuspects")
                        .HasForeignKey("ProsecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd_Api.Models.Suspect", "Suspect")
                        .WithMany("ProsecutionSuspects")
                        .HasForeignKey("SuspectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Prosecution");

                    b.Navigation("Suspect");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Question", b =>
                {
                    b.HasOne("BackEnd_Api.Models.User", "User")
                        .WithMany("Questions")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackEnd_Api.Models.Interview", "Interview")
                        .WithMany("Questions")
                        .HasForeignKey("InterviewId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Interview");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackEnd_Api.Models.RecordInfo", b =>
                {
                    b.HasOne("BackEnd_Api.Models.Evidence", "Evidence")
                        .WithMany("RecordInfos")
                        .HasForeignKey("EvidenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Report", b =>
                {
                    b.HasOne("BackEnd_Api.Models.Case", "Case")
                        .WithMany("Reports")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BackEnd_Api.Models.User", "User")
                        .WithMany("Reports")
                        .HasForeignKey("OfficerApproveId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Case");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackEnd_Api.Models.ReportSuspect", b =>
                {
                    b.HasOne("BackEnd_Api.Models.Report", "Report")
                        .WithMany("ReportSuspects")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd_Api.Models.Suspect", "Suspect")
                        .WithMany("ReportSuspects")
                        .HasForeignKey("SuspectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Report");

                    b.Navigation("Suspect");
                });

            modelBuilder.Entity("BackEnd_Api.Models.ReportVictim", b =>
                {
                    b.HasOne("BackEnd_Api.Models.Report", "Report")
                        .WithMany("ReportVictims")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd_Api.Models.Victim", "Victim")
                        .WithMany("ReportVictims")
                        .HasForeignKey("VictimId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Report");

                    b.Navigation("Victim");
                });

            modelBuilder.Entity("BackEnd_Api.Models.ReportWitness", b =>
                {
                    b.HasOne("BackEnd_Api.Models.Report", "Report")
                        .WithMany("ReportWitness")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd_Api.Models.Witness", "Witness")
                        .WithMany("ReportWitness")
                        .HasForeignKey("WitnessId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Report");

                    b.Navigation("Witness");
                });

            modelBuilder.Entity("BackEnd_Api.Models.RolePermission", b =>
                {
                    b.HasOne("BackEnd_Api.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd_Api.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BackEnd_Api.Models.SceneDescription", b =>
                {
                    b.HasOne("BackEnd_Api.Models.Case", "Case")
                        .WithMany("SceneDescription")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd_Api.Models.User", "User")
                        .WithMany("SceneDescriptions")
                        .HasForeignKey("Provider")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackEnd_Api.Models.SceneMedia", b =>
                {
                    b.HasOne("BackEnd_Api.Models.User", "User")
                        .WithMany("SceneMedias")
                        .HasForeignKey("CapturedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackEnd_Api.Models.Case", "Case")
                        .WithMany("SceneMedia")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackEnd_Api.Models.SceneProtection", b =>
                {
                    b.HasOne("BackEnd_Api.Models.Case", "Case")
                        .WithMany("SceneProtections")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("BackEnd_Api.Models.SceneSuport", b =>
                {
                    b.HasOne("BackEnd_Api.Models.Case", "Case")
                        .WithMany("SceneSuports")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Sentence", b =>
                {
                    b.HasOne("BackEnd_Api.Models.Case", "Case")
                        .WithMany("Sentences")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BackEnd_Api.Models.CaseResult", "CaseResult")
                        .WithMany("Sentences")
                        .HasForeignKey("CaseResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("CaseResult");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Suspect", b =>
                {
                    b.HasOne("BackEnd_Api.Models.Case", "Case")
                        .WithMany("Suspects")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("BackEnd_Api.Models.SuspectEvidence", b =>
                {
                    b.HasOne("BackEnd_Api.Models.Evidence", "Evidence")
                        .WithMany("SuspectEvidences")
                        .HasForeignKey("EvidenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackEnd_Api.Models.Suspect", "Suspect")
                        .WithMany("SuspectEvidences")
                        .HasForeignKey("SuspectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Evidence");

                    b.Navigation("Suspect");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Timeline", b =>
                {
                    b.HasOne("BackEnd_Api.Models.CaseResult", "CaseResult")
                        .WithMany("Timelines")
                        .HasForeignKey("CaseResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaseResult");
                });

            modelBuilder.Entity("BackEnd_Api.Models.User", b =>
                {
                    b.HasOne("BackEnd_Api.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BackEnd_Api.Models.UserCase", b =>
                {
                    b.HasOne("BackEnd_Api.Models.Case", "Case")
                        .WithMany("UserCases")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd_Api.Models.User", "User")
                        .WithMany("UserCases")
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Victim", b =>
                {
                    b.HasOne("BackEnd_Api.Models.Case", "Case")
                        .WithMany("Victims")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("BackEnd_Api.Models.VictimEvidence", b =>
                {
                    b.HasOne("BackEnd_Api.Models.Evidence", "Evidence")
                        .WithMany("VictimEvidences")
                        .HasForeignKey("EvidenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackEnd_Api.Models.Victim", "Victim")
                        .WithMany("VictimEvidences")
                        .HasForeignKey("VictimId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Evidence");

                    b.Navigation("Victim");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Warrant", b =>
                {
                    b.HasOne("BackEnd_Api.Models.Case", "Case")
                        .WithMany("Warrants")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd_Api.Models.User", "User")
                        .WithMany("Warrants")
                        .HasForeignKey("PoliceReponse")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackEnd_Api.Models.WarrantEvidence", b =>
                {
                    b.HasOne("BackEnd_Api.Models.Evidence", "Evidence")
                        .WithMany("WarrantEvidences")
                        .HasForeignKey("EvidenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackEnd_Api.Models.Warrant", "Warrant")
                        .WithMany("WarrantEvidences")
                        .HasForeignKey("WarrantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evidence");

                    b.Navigation("Warrant");
                });

            modelBuilder.Entity("BackEnd_Api.Models.WarrantResult", b =>
                {
                    b.HasOne("BackEnd_Api.Models.User", "User")
                        .WithMany("WarrantResults")
                        .HasForeignKey("PoliceResponse")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackEnd_Api.Models.Warrant", "Warrant")
                        .WithMany("WarrantResults")
                        .HasForeignKey("WarrantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Warrant");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Witness", b =>
                {
                    b.HasOne("BackEnd_Api.Models.Case", "Case")
                        .WithMany("Witnesses")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Case", b =>
                {
                    b.Navigation("Arrests");

                    b.Navigation("CaseEvidences");

                    b.Navigation("CaseResults");

                    b.Navigation("Events");

                    b.Navigation("InvestigationPlans");

                    b.Navigation("Prosecutions");

                    b.Navigation("Reports");

                    b.Navigation("SceneDescription");

                    b.Navigation("SceneMedia");

                    b.Navigation("SceneProtections");

                    b.Navigation("SceneSuports");

                    b.Navigation("Sentences");

                    b.Navigation("Suspects");

                    b.Navigation("UserCases");

                    b.Navigation("Victims");

                    b.Navigation("Warrants");

                    b.Navigation("Witnesses");
                });

            modelBuilder.Entity("BackEnd_Api.Models.CaseResult", b =>
                {
                    b.Navigation("Sentences");

                    b.Navigation("Timelines");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Evidence", b =>
                {
                    b.Navigation("CaseEvidences");

                    b.Navigation("DigitalInvest")
                        .IsRequired();

                    b.Navigation("FinancialInvest")
                        .IsRequired();

                    b.Navigation("ForensicInvest")
                        .IsRequired();

                    b.Navigation("PhysicalInvest")
                        .IsRequired();

                    b.Navigation("RecordInfos");

                    b.Navigation("SuspectEvidences");

                    b.Navigation("VictimEvidences");

                    b.Navigation("WarrantEvidences");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Interview", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("BackEnd_Api.Models.InvestigationPlan", b =>
                {
                    b.Navigation("Interviews");
                });

            modelBuilder.Entity("BackEnd_Api.Models.MeasureSurvey", b =>
                {
                    b.Navigation("Evidences");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Prosecution", b =>
                {
                    b.Navigation("Indictments");

                    b.Navigation("ProsecutionSuspects");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Report", b =>
                {
                    b.Navigation("Evidences");

                    b.Navigation("ReportSuspects");

                    b.Navigation("ReportVictims");

                    b.Navigation("ReportWitness");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Sentence", b =>
                {
                    b.Navigation("Inmates");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Suspect", b =>
                {
                    b.Navigation("Arrests");

                    b.Navigation("Events");

                    b.Navigation("ProsecutionSuspects");

                    b.Navigation("ReportSuspects");

                    b.Navigation("SuspectEvidences");
                });

            modelBuilder.Entity("BackEnd_Api.Models.User", b =>
                {
                    b.Navigation("Arrests");

                    b.Navigation("Evidences");

                    b.Navigation("Interviews");

                    b.Navigation("InvestigationPlans");

                    b.Navigation("Prosecutions");

                    b.Navigation("Questions");

                    b.Navigation("Reports");

                    b.Navigation("SceneDescriptions");

                    b.Navigation("SceneMedias");

                    b.Navigation("UserCases");

                    b.Navigation("WarrantResults");

                    b.Navigation("Warrants");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Victim", b =>
                {
                    b.Navigation("ReportVictims");

                    b.Navigation("VictimEvidences");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Warrant", b =>
                {
                    b.Navigation("WarrantEvidences");

                    b.Navigation("WarrantResults");
                });

            modelBuilder.Entity("BackEnd_Api.Models.WarrantResult", b =>
                {
                    b.Navigation("Evidences");
                });

            modelBuilder.Entity("BackEnd_Api.Models.Witness", b =>
                {
                    b.Navigation("ReportWitness");
                });
#pragma warning restore 612, 618
        }
    }
}
