export const roleMap = {
  "1": "Admin",
  "2": "Patrol Officer",
  "3": "Investigator",
  "4": "Forensic Analyst",
  "5": "Prosecutor",
  "6": "Financial Analyst",
  "7": "Evidence Custodian",
  "8": "Chief of Police",
  "9": "Detective",
  "10": "Cybercrime Specialist",
  "11": "Report Approver",
  "12": "Legal Counsel",
  "13": "Records Manager",
  "14": "Public Relations Officer",
  "15": "Training Officer",
  "16": "Field Officer",
  "17": "Case Manager",
  "18": "Security Analyst",
  "19": "Witness Protection Officer",
  "20": "Intelligence Analyst",
};